### ISSUE TITLE
Will Obfuscar run correctly with .Net 8 projects? I can't get it to run.

### ISSUE THREAD

**Issue by jurassicjp** [obfuscar/obfuscar#477]
We are trying to get Obfuscar to run on our assembly developed for .Net 8 to obfuscate our code. We have no experience with obfuscation or Obfuscar. We were able to get it to run correctly with .Net Framework, but we are getting errors with .Net 8.

If we Build our project, we get following error:
The command ""C:\Users\xx.xx\.nuget\packages\obfuscar\2.2.38\build\..\tools\Obfuscar.Console.exe" obfuscar.xml" exited with code 1.

When we try to install the nuget GlobalTool we get following error:
Package Obfuscar.GlobalTool 2.2.38 is not compatible with net8.0 (.NETCoreApp,Version=v8.0). Package Obfuscar.GlobalTool 2.2.38 supports:  - net6.0 (.NETCoreApp,Version=v6.0) / any  - net7.0 (.NETCoreApp,Version=v7.0) / any  - net8.0 (.NETCoreApp,Version=v8.0) / any

our Test Project is .Net 8

find attached our test project.

No idea how to get this run on a .Net 8 assembly.

Any help would be greatly appreciated.
Thanks a lot
[obfuscartest.zip](https://github.com/user-attachments/files/16588091/obfuscartest.zip)

**Comment by lextm** [comment]
Fixed in release 2.2.39.

**Comment by jurassicjp** [comment]
Hi Lextm, thanks for your very quick response. I really appreciate it.
When we install Nuget Obfuscar.GlobalTool 2.2.39, we still get the following error:

Severity              Code     Description      Project File        Line       Suppression State
Error     NU1202              Package Obfuscar.GlobalTool 2.2.39 is not compatible with net8.0 (.NETCoreApp,Version=v8.0). Package Obfuscar.GlobalTool 2.2.39 supports:
  - net6.0 (.NETCoreApp,Version=v6.0) / any
  - net8.0 (.NETCoreApp,Version=v8.0) / any     obfuscartest                C:\CTE_Source\obfuscartest\obfuscartest\obfuscartest.csproj         1             
Error                     Package 'Obfuscar.GlobalTool 2.2.39' has a package type 'DotnetTool' that is not supported by project 'obfuscartest'.                                                 


[obfuscartest.zip](https://github.com/user-attachments/files/16610912/obfuscartest.zip)

And the obfuscation we get is very little, see the attached zip in folder C:\TEMP\obfuscartest.zip\obfuscartest\obfuscartest\bin\Release\net8.0\obfuscated

**Comment by lextm** [comment]
The global tool is supposed to be run at terminal, not as package dependency,

https://docs.lextudio.com/obfuscar/getting-started/basics.html

**Comment by mpahee** [comment]
I am using the latest version (2.2.49.0), it return error for .Net 8.0
